/*
 * Asset URLs for the human pipeline (generated by tools/human/*.py into src/assets/human/).
 * Vite turns every file into a URL (multi-file build) or a data: URI (single-file build, where every preset's
 * files end up embedded in the page). Files are imported lazily, so nothing is fetched until a preset loads.
 */
type Loader = () => Promise<string>;

// eager URL strings (not the files): nothing is downloaded until a preset asks for it, and the build needs no stub
// chunk per file (fewer files to publish, one round trip less per asset)
const URLS = import.meta.glob('../../assets/human/**/*.{json,binz,webp,jpg,png}', { query: '?url', import: 'default', eager: true }) as Record<string, string>;
const FILES: Record<string, Loader> = Object.fromEntries(Object.entries(URLS).map(([k, u]) => [k, () => Promise.resolve(u)]));

const PREFIX = '../../assets/human/';

/** Resolve an asset path relative to src/assets/human/ (e.g. "david/rig.json") to a URL. */
export async function humanAssetUrl(rel: string): Promise<string> {
  const f = FILES[PREFIX + rel];
  if (!f) throw new Error(`human asset not found: ${rel}`);
  return f();
}

export function hasHumanAsset(rel: string) {
  return PREFIX + rel in FILES;
}
