/**
 * META strings: trick names, challenges, ranks, replay / clip / photo UI.
 * UI merges these through addStrings(). Variables use the `{name}` syntax.
 */

const en: Record<string, string> = {
  // Tricks
  'trick.returnToSender': 'RETURN TO SENDER',
  'trick.crossfire': 'CROSSFIRE',
  'trick.postage': 'POSTAGE',
  'trick.firingLine': 'FIRING LINE',
  'trick.borrowedGun': 'BORROWED GUN',
  'trick.trapdoor': 'TRAPDOOR',
  'trick.splashdown': 'SPLASHDOWN',
  'trick.void': 'INTO THE VOID',
  'trick.skyfall': 'SKYFALL',
  'trick.matador': 'MATADOR',
  'trick.bowling': 'BOWLING',
  'trick.headsUp': 'HEADS UP',
  'trick.loop': 'LOOP',
  'trick.cannonball': 'CANNONBALL',
  'trick.slingshot': 'SLINGSHOT',
  'trick.comet': 'COMET',
  'trick.guillotine': 'GUILLOTINE',
  'trick.cargo': 'CARGO',
  'trick.boom': 'BOOM',
  'trick.finisher': 'FINISHER',
  'trick.ghost': 'GHOST',
  'trick.airtime': 'AIRTIME',
  'trick.double': 'DOUBLE',
  'trick.triple': 'TRIPLE',
  'trick.multi': 'MULTI',
  'trick.mirror': 'MIRROR',
  'trick.hijack': 'HIJACK',
  'trick.juggle': 'JUGGLE',
  'trick.geyser': 'GEYSER',
  'trick.express': 'EXPRESS DROP',
  'trick.reflect': 'REFLECT',

  // Style
  'rank.D': 'D', 'rank.C': 'C', 'rank.B': 'B', 'rank.A': 'A', 'rank.S': 'S', 'rank.SS': 'SS', 'rank.SSS': 'SSS',
  'style.label': 'STYLE',
  'style.combo': 'COMBO',
  'style.halved': 'REPEAT ½',

  // Zone challenges
  'challenge.pier.1.title': 'Return to Sender ×3',
  'challenge.pier.1.desc': 'Kill three Kessler guards with bolts they fired themselves.',
  'challenge.pier.2.title': 'Double Dip',
  'challenge.pier.2.desc': 'Drown two Kessler guards within 3 seconds of each other.',
  'challenge.pier.3.title': 'Pier Pressure',
  'challenge.pier.3.desc': 'Reach an S style rank on the pier.',
  'challenge.yard.1.title': 'Special Delivery',
  'challenge.yard.1.desc': 'Kill a guard with a falling load (CARGO).',
  'challenge.yard.2.title': 'Olé',
  'challenge.yard.2.desc': 'MATADOR the brute into the sea: his charge into your entrance, out over the water.',
  'challenge.yard.3.title': 'Frequent Flyer',
  'challenge.yard.3.desc': 'Stay airborne for 5 seconds with at least one rift crossing (AIRTIME).',
  'challenge.skeleton.1.title': 'Round and Round',
  'challenge.skeleton.1.desc': 'Loop something through your rifts six times in a row (LOOP ×6).',
  'challenge.skeleton.2.title': 'Line of Fire',
  'challenge.skeleton.2.desc': "Catch the sniper's beam and send it into a Kessler guard (FIRING LINE).",
  'challenge.skeleton.3.title': 'Cannonball!',
  'challenge.skeleton.3.desc': 'Kill with something that looped through your rifts at least twice.',
  'challenge.lab.1.title': 'Under New Management',
  'challenge.lab.1.desc': 'Hijack both Kessler rift gates.',
  'challenge.lab.2.title': 'Borrowed Twice',
  'challenge.lab.2.desc': 'Kill two guards with caught turret rounds (BORROWED GUN ×2).',
  'challenge.lab.3.title': 'Strike!',
  'challenge.lab.3.desc': 'Knock down or kill two guards with one flung body (BOWLING).',
  'challenge.crown.1.title': 'Hostile Takeover',
  'challenge.crown.1.desc': 'Defeat Director Voss.',
  'challenge.crown.2.title': 'Executive Cannonball',
  'challenge.crown.2.desc': 'Hit Director Voss with something that looped through your rifts at least twice.',
  'challenge.crown.3.title': 'Leap of Faith',
  'challenge.crown.3.desc': 'Jump off the crown and let a rift catch you.',

  // Daily challenge (vars: {trick} localized trick name, {n}, {s}, {points})
  'challenge.daily.title': 'DAILY: {trick}',
  'challenge.daily.count.desc': 'Land {trick} ×{n} today.',
  'challenge.daily.within.desc': 'Land {trick} twice within {s} seconds.',
  'challenge.daily.combo.desc': 'Reach a {points}-point combo that includes {trick}.',
  'challenge.daily.air.desc': 'Land {trick} while you are in the air.',
  'challenge.daily.ghost.desc': 'Land {trick} on a guard nobody sees die.',
  'challenge.daily.label': 'DAILY',
  'challenge.complete': 'CHALLENGE COMPLETE',
  'challenge.progress': '{n}/{m}',

  // Replay / clip overlay + UI
  'replay.title': 'REPLAY',
  'replay.tag': 'RIFT ACTION',
  'replay.combo': 'COMBO',
  'replay.skip': 'SKIP',
  'replay.slowmo': 'SLOW-MO',
  'replay.end': 'MADE IN THRESHOLD',
  'clip.offer': 'CLIP',
  'clip.recording': 'REC',
  'clip.exporting': 'SAVING CLIP…',
  'clip.share': 'SHARE CLIP',
  'clip.download': 'SAVE CLIP',
  'clip.unsupported': "This browser can't record clips. Watch the replay instead.",
  'clip.shared': 'Clip shared',
  'clip.saved': 'Clip saved',
  'clip.failed': "Couldn't save the clip",

  // Photo mode
  'photo.title': 'PHOTO MODE',
  'photo.snap': 'SNAP',
  'photo.exit': 'BACK',
  'photo.fov': 'FOV',
  'photo.roll': 'TILT',
  'photo.hint': 'Mouse to look · WASD to move · wheel to zoom · click to snap · P to leave',
  'photo.hint.touch': 'Drag to look · pinch or +/− to zoom',
  'photo.saved': 'Photo saved',
};

const he: Record<string, string> = {
  // Tricks
  'trick.returnToSender': 'החזרה לשולח',
  'trick.crossfire': 'אש צולבת',
  'trick.postage': 'משלוח',
  'trick.firingLine': 'קו האש',
  'trick.borrowedGun': 'נשק שאול',
  'trick.trapdoor': 'דלת מלכודת',
  'trick.splashdown': 'צלילה',
  'trick.void': 'אל התהום',
  'trick.skyfall': 'נפילה מהשמיים',
  'trick.matador': 'מטדור',
  'trick.bowling': 'באולינג',
  'trick.headsUp': 'זהירות מלמעלה',
  'trick.loop': 'לולאה',
  'trick.cannonball': 'כדור תותח',
  'trick.slingshot': 'רוגטקה',
  'trick.comet': 'שביט',
  'trick.guillotine': 'גיליוטינה',
  'trick.cargo': 'מטען',
  'trick.boom': 'בום',
  'trick.finisher': 'מכת חסד',
  'trick.ghost': 'רוח רפאים',
  'trick.airtime': 'ריחוף',
  'trick.double': 'כפול',
  'trick.triple': 'משולש',
  'trick.multi': 'מולטי',
  'trick.mirror': 'מראה',
  'trick.hijack': 'חטיפה',
  'trick.juggle': 'להטוטן',
  'trick.geyser': 'גייזר',
  'trick.express': 'משלוח אקספרס',
  'trick.reflect': 'השתקפות',

  // Style
  'rank.D': 'D', 'rank.C': 'C', 'rank.B': 'B', 'rank.A': 'A', 'rank.S': 'S', 'rank.SS': 'SS', 'rank.SSS': 'SSS',
  'style.label': 'סטייל',
  'style.combo': 'קומבו',
  'style.halved': 'חזרה ½',

  // Zone challenges
  'challenge.pier.1.title': 'החזרה לשולח ×3',
  'challenge.pier.1.desc': 'חסלו שלושה שומרי קסלר עם כדורים שהם עצמם ירו.',
  'challenge.pier.2.title': 'טבילה כפולה',
  'challenge.pier.2.desc': 'הטביעו שני שומרי קסלר בהפרש של עד 3 שניות.',
  'challenge.pier.3.title': 'לחץ על המזח',
  'challenge.pier.3.desc': 'הגיעו לדרגת סטייל S על המזח.',
  'challenge.yard.1.title': 'משלוח מיוחד',
  'challenge.yard.1.desc': 'חסלו שומר עם מטען נופל (מטען).',
  'challenge.yard.2.title': 'אולה',
  'challenge.yard.2.desc': 'מטדור לבריון אל הים: ההסתערות שלו לתוך הכניסה, והחוצה מעל המים.',
  'challenge.yard.3.title': 'נוסע מתמיד',
  'challenge.yard.3.desc': 'הישארו באוויר 5 שניות עם לפחות מעבר אחד בשער (ריחוף).',
  'challenge.skeleton.1.title': 'סחרחורת',
  'challenge.skeleton.1.desc': 'העבירו משהו בלולאה דרך השערים שש פעמים ברצף (לולאה ×6).',
  'challenge.skeleton.2.title': 'על קו האש',
  'challenge.skeleton.2.desc': 'תפסו את קרן הצלף ושלחו אותה לשומר קסלר (קו האש).',
  'challenge.skeleton.3.title': 'כדור תותח!',
  'challenge.skeleton.3.desc': 'חסלו עם משהו שעבר בלולאה דרך השערים לפחות פעמיים.',
  'challenge.lab.1.title': 'הנהלה חדשה',
  'challenge.lab.1.desc': 'חטפו את שני שערי הקרע של קסלר.',
  'challenge.lab.2.title': 'שאול פעמיים',
  'challenge.lab.2.desc': 'חסלו שני שומרים עם צרורות צריח שתפסתם (נשק שאול ×2).',
  'challenge.lab.3.title': 'סטרייק!',
  'challenge.lab.3.desc': 'הפילו או חסלו שני שומרים עם גוף אחד שעף (באולינג).',
  'challenge.crown.1.title': 'השתלטות עוינת',
  'challenge.crown.1.desc': 'הביסו את המנהל ווס.',
  'challenge.crown.2.title': 'כדור תותח למנכ״ל',
  'challenge.crown.2.desc': 'פגעו במנהל ווס עם משהו שעבר בלולאה דרך השערים לפחות פעמיים.',
  'challenge.crown.3.title': 'קפיצת אמונה',
  'challenge.crown.3.desc': 'קפצו מהגג ותנו לשער לתפוס אתכם.',

  // Daily
  'challenge.daily.title': 'יומי: {trick}',
  'challenge.daily.count.desc': 'בצעו {trick} ×{n} היום.',
  'challenge.daily.within.desc': 'בצעו {trick} פעמיים בתוך {s} שניות.',
  'challenge.daily.combo.desc': 'הגיעו לקומבו של {points} נקודות שכולל {trick}.',
  'challenge.daily.air.desc': 'בצעו {trick} כשאתם באוויר.',
  'challenge.daily.ghost.desc': 'בצעו {trick} על שומר שאף אחד לא רואה מת.',
  'challenge.daily.label': 'יומי',
  'challenge.complete': 'אתגר הושלם',
  'challenge.progress': '{n}/{m}',

  // Replay / clip
  'replay.title': 'שידור חוזר',
  'replay.tag': 'אקשן של שערים',
  'replay.combo': 'קומבו',
  'replay.skip': 'דלג',
  'replay.slowmo': 'הילוך איטי',
  'replay.end': 'נוצר ב-THRESHOLD',
  'clip.offer': 'קליפ',
  'clip.recording': 'מקליט',
  'clip.exporting': 'שומר קליפ…',
  'clip.share': 'שתפו קליפ',
  'clip.download': 'שמרו קליפ',
  'clip.unsupported': 'הדפדפן הזה לא יכול להקליט קליפים. צפו בשידור החוזר במקום.',
  'clip.shared': 'הקליפ שותף',
  'clip.saved': 'הקליפ נשמר',
  'clip.failed': 'לא הצלחנו לשמור את הקליפ',

  // Photo mode
  'photo.title': 'מצב צילום',
  'photo.snap': 'צלם',
  'photo.exit': 'חזרה',
  'photo.fov': 'זווית',
  'photo.roll': 'הטיה',
  'photo.hint': 'עכבר להסתכל · WASD לזוז · גלגלת לזום · קליק לצילום · P ליציאה',
  'photo.hint.touch': 'גררו כדי להסתכל · צביטה או +/− לזום',
  'photo.saved': 'התמונה נשמרה',
};

export const META_STRINGS: { en: Record<string, string>; he: Record<string, string> } = { en, he };

export type MetaLang = 'en' | 'he';

/** Look up a META string (falls back to English, then the key) and fill `{vars}`. */
export function metaText(key: string, lang: MetaLang = 'en', vars?: Record<string, string | number>): string {
  let s = META_STRINGS[lang][key] ?? META_STRINGS.en[key] ?? key;
  if (vars) for (const k in vars) s = s.split(`{${k}}`).join(String(vars[k]));
  return s;
}
