export const GAME_CONFIG = {
  physicsHz: 60,
  gravity: { x: 0, y: -5.8, z: 0 },
  arenaRadius: 5.4,
  postureKoHeight: 0.62,
  postureKoSeconds: 3.2,
  puppet: {
    anchorPull: 118,
    anchorDamping: 15,
    strikePull: 82,
    strikeDamping: 10,
    snapImpulse: 3.4,
    balanceTorque: 15,
    balanceDamping: 4,
    musclePull: 38,
    muscleDamping: 8,
    maxSpeed: 5.8,
  },
  stamina: {
    max: 100,
    regenPerSecond: 18,
    anchorCostPerSecond: 0.8,
    strikeCostPerSecond: 18,
    slackThreshold: 1,
    slackSeconds: 0.85,
  },
  replaySeconds: 8,
  seed: 1337,
} as const;
